### ISSUE TITLE
Support for Origin and Centos

### ISSUE THREAD

**Issue by tdudgeon** [ktenzer/openshift-on-openstack-123#3]
These playbooks look great, but it seems they are targeted only at RHEL and OpenShift Enterprise.
Will it be possible to run on Centos and Origin?

**Comment by ktenzer** [comment]
Hi Tim,

Yeah I work at Red Hat so I don't get a lot of time to work on community
stuff and more with the enterprise products. Things should work, the only
thing you need to do is setup the repos required and disable the
subscription management. If you would be willing to test this I could
certainly help and if you create option for CentOS and Origin or RHEL and
OpenShift + get it working I would gladly accept your pull request.

Let me know?

Keith

**Comment by ktenzer** [comment]
OKD (origin) tested and working on centos 7.5 so closing issue.
