### ISSUE TITLE
json format issue release 1

### ISSUE THREAD

**Issue by compendius** [ktenzer/openshift-on-openstack-123#4]
RHOSP11 and RHEL 7.4

Needed to change all these sections in these files  - 

openshift-on-openstack-123/roles/osp-stack-create/tasks/main.yml
openshift-on-openstack-123/roles/osp-inventory/tasks/main.yml

```
- name: Register stack output
  command: >
    openstack stack output show -f value -c output_value
    {{ stack_name }} ip_address
  register: stack_output_raw
```

to json formatting - 

```
- name: Register stack output
  command: >
    openstack stack output show -f json -c output_value
    {{ stack_name }} ip_address
  register: stack_output_raw
```

Needed to also change several references in this file

openshift-on-openstack-123/roles/osp-inventory/tasks/main.yml

as the json object path was incorrect. Needed to add 'output_value' for example

```
name: "{{ stack_output.bastion.name }}"
```

becomes

```
name: "{{ stack_output.output_value.bastion.name }}"
```

This now works
I think this is related to the python openstack client version used. For example I am running this deployment from a dedicated RHEL74 instance in a dedicated test project in our production cloud. Depending on the openstack  client version the json formatting can be full of '\n' which breaks things.

**Comment by ktenzer** [comment]
Can you do a pull request happy to accept these changes

**Comment by ktenzer** [comment]
And huge thanks for contributing!

**Comment by compendius** [comment]
Will do. I am just finishing my deployment testing to make sure there are no other related  issues

**Comment by compendius** [comment]
I will not make the pull request as I can see that with the issues definately lies with the OSP11 python openstack client and the json output. If I use the OSP12 python openstack client your original config works fine.
So in my OSP11 environment I opt for the OSP 12 version in the vars.yml file and all works. This configures the  rhel-7-server-openstack-12-tools-rpms repo which works fine with OSP11.

**Comment by ktenzer** [comment]
this should be fixed now so closing
